import { GoogleGenerativeAI } from "@google/generative-ai";
import { ProductDeal, CampaignOutput, ProductForScript } from "../types";
import { generateYouTubeContentForCampaign } from "../services/youtubeContentService";

const genAI = new GoogleGenerativeAI(import.meta.env.VITE_GEMINI_API_KEY || process.env.VITE_GEMINI_API_KEY || '');

// Helper: Convert price to TTS-friendly format
function formatPriceForTTS(price: string): string {
  const num = parseFloat(price);
  if (isNaN(num)) return price;
  
  const dollars = Math.floor(num);
  const cents = Math.round((num - dollars) * 100);
  
  if (num < 1) {
    return `${Math.round(num * 100)} cents`;
  } else if (cents === 0) {
    return `${dollars} dollars`;
  } else {
    // Use conversational style
    if (cents < 10) {
      return `just over ${dollars} dollars`;
    } else if (cents > 90) {
      return `under ${dollars + 1} bucks`;
    } else {
      return `${dollars} dollars and ${cents} cents`;
    }
  }
}

// Helper: Create clean product name
function createCleanName(title: string): string {
  if (!title) return "Product";
  
  // Remove common filler words
  const fillers = [
    /ideal gift/gi,
    /ages \d+-\d+/gi,
    /stem/gi,
    /road trip/gi,
    /educational/gi,
    /premium quality/gi,
    /best seller/gi,
    /top rated/gi,
    /\([^)]*\)/g // Remove parentheses content
  ];
  
  let clean = title;
  fillers.forEach(pattern => {
    clean = clean.replace(pattern, '');
  });
  
  // Clean up extra spaces and limit length
  clean = clean.replace(/\s+/g, ' ').trim();
  
  // Limit to ~50 chars for readability
  if (clean.length > 50) {
    clean = clean.substring(0, 50).trim() + '...';
  }
  
  return clean || title.substring(0, 50);
}

// Helper: Calculate sale price from discount
function calculateSalePrice(regularPrice: string, discount: string): string {
  const reg = parseFloat(regularPrice);
  const disc = parseFloat(discount);
  
  if (isNaN(reg) || isNaN(disc)) return regularPrice;
  
  const salePrice = reg * (1 - disc / 100);
  return salePrice.toFixed(2);
}

// Process product deal into script format
function processProduct(deal: ProductDeal): ProductForScript {
  const cleanName = createCleanName(deal.title || 'Product');
  
  // Determine regular and sale prices
  let regularPrice = deal.price || '0';
  let salePrice = deal.price || '0';
  
  // If we have a discount, calculate sale price
  if (deal.discount) {
    const discountNum = parseFloat(deal.discount);
    if (!isNaN(discountNum)) {
      salePrice = calculateSalePrice(regularPrice, deal.discount);
    }
  }
  
  return {
    asin: deal.asin,
    cleanName,
    regularPrice,
    salePrice,
    code: deal.code || 'None shown',
    discount: deal.discount || '0',
    imageUrl: deal.imageUrl || '',
    link: `https://www.amazon.com/dp/${deal.asin}`,
    wittyLine: '' // Will be generated by AI
  };
}

export const generateGirlMathCampaign = async (deals: ProductDeal[]): Promise<CampaignOutput> => {
  const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash-exp" });
  
  // Process all products
  const products = deals.map(processProduct);
  
  // Build prompt for Gemini following the exact rules
  const prompt = `You are a product-analysis assistant for an Amazon Influencer, creating scripts for TikTok/Reels.

I have ${products.length} products. For EACH product, generate a witty "girl math" hook line following these STRICT rules:

WITTY LINE FORMULA:
1. Structure: Start with a hook that frames the deal, then state the money in TTS-friendly format
2. Vibe Flavors (mix these):
   - Girl Math: "That's basically like getting paid to buy it"
   - Treat Yourself: "You were good all week, this is your reward"
   - Playful Sarcasm: "Tell your husband it was more expensive"
   - Social Proof: "Everyone's grabbing these right now"
3. MUST include specific dollar amounts in TTS format (see below)
4. If code exists, use GENERIC phrases like "use this code", "grab the code", "apply this code" - NEVER say the actual code name
5. AVOID: "just", "only", "cheap", generic phrases, and NEVER mention the actual code (like A2AWMA3142FVVY)

TTS-FRIENDLY PRICE RULES:
- Whole dollars: "X dollars" (e.g., $12 = "12 dollars")
- Under $1: "X cents" (e.g., $0.99 = "99 cents")  
- With cents: Use conversational style like "just over X dollars" or "under X bucks"
- Savings: Phrase naturally like "saving you 5 dollars" or "that's 20 bucks off"

PRODUCTS:
${products.map((p, i) => `
${i + 1}. ${p.cleanName}
   Regular: $${p.regularPrice}
   Sale: $${p.salePrice}
   Has Code: ${p.code !== 'None shown' ? 'Yes' : 'No'}
   Discount: ${p.discount}%
`).join('\n')}

Return ONLY a JSON object with this structure:
{
  "products": [
    {
      "asin": "...",
      "wittyLine": "Your generated witty hook here following all rules above"
    }
  ]
}

Remember: The witty line must be TTS-friendly, playful, include specific prices, follow girl-math logic, and use "use this code" NOT the actual code name.`;

  try {
    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();
    
    // Extract JSON from markdown code blocks if present
    const jsonMatch = text.match(/```json\n([\s\S]*?)\n```/) || text.match(/```\n([\s\S]*?)\n```/);
    const jsonText = jsonMatch ? jsonMatch[1] : text;
    
    const aiResponse = JSON.parse(jsonText);
    
    // Match witty lines to products
    aiResponse.products.forEach((aiProduct: any, index: number) => {
      if (products[index]) {
        products[index].wittyLine = aiProduct.wittyLine;
      }
    });
    
  } catch (error) {
    console.error('AI generation failed, using fallback witty lines:', error);
    // Fallback witty lines if AI fails
    products.forEach(p => {
      const savings = (parseFloat(p.regularPrice) - parseFloat(p.salePrice)).toFixed(2);
      const hasCode = p.code !== 'None shown';
      
      p.wittyLine = hasCode 
        ? `Tell your partner it was full price... ${formatPriceForTTS(p.salePrice)} with the code is your little secret.`
        : `For ${formatPriceForTTS(p.salePrice)}? That's basically free in girl math.`;
    });
  }
  
  // Build video script
  const intro = "My wallet might be mad, but my self-care is thriving. Consider this your emergency retail therapy session.";
  
  const productLines = products.map(p => 
    `This is the ${p.cleanName}. ${p.wittyLine}`
  ).join('\n\n<#0.5#>\n\n');
  
  const outro = "Link in my bio with the codes. <#0.5#> The girl math is mathing on this one!";
  
  const videoScript = `${intro}\n\n${productLines}\n\n${outro}`;
  
  // Build editing summary
  const editingSummary = products.map(p => 
    `${p.cleanName}\n${p.code}`
  ).join('\n\n');
  
  // Build CSV
  const csvHeader = 'Title,Link,RegularPrice,SalePrice,Code';
  const csvRows = products.map(p => 
    `"${p.cleanName}","${p.link}",$${p.regularPrice},$${p.salePrice},${p.code}`
  );
  const csvContent = `${csvHeader}\n${csvRows.join('\n')}`;
  
  // Generate YouTube content
  const youtubeContent = generateYouTubeContentForCampaign(products);

  return {
    persona: 'girlmath',
    videoScript,
    editingSummary,
    csvContent,
    products,
    youtubeContent
  };
};
